### ISSUE TITLE
Bug with 6.0.0 or 6.11.0

### ISSUE THREAD

**Issue by jasonkarns** [nodenv/node-build-update-defs#12]
```
Error: bad checksum data
    at sourcePackage (/usr/local/var/nodenv/plugins/node-build-update-defs/lib/build-node.js:60:13)
    at Object.<anonymous> (/usr/local/var/nodenv/plugins/node-build-update-defs/lib/build-node.js:28:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by jasonkarns** [comment]
closed by #14
